### ISSUE TITLE
大佬，更新后百合会签到还是失败而且推送的消息内容不全

### ISSUE THREAD

**Issue by koitoyuu19** [jckling/Daily-Bonus#10]
「Yamibo」
签到信息: 未知错误
————————————

开始时间: 2022-11-28 19:38:44
任务用时: 1 秒

================================

开始时间: 2022-11-29 07:38:02
任务用时: 0 秒

上面是更新之前的消息，今天更新了分支，按照文档配置了环境变量，结果签到失败而且推送的消息内容变成只有时间了

**Comment by jckling** [comment]
我判断条件写错了，刚更新 :joy:

1. 配置 `YAMIBO_EeqY_2132_saltkey` 和 `YAMIBO_EeqY_2132_auth`
2. 更新分支，应该会触发新的 Action

运行效果如下：

![image](https://user-images.githubusercontent.com/25079277/204471146-347b2153-fd3c-47e7-8342-9c099df094b7.png)

**Comment by koitoyuu19** [comment]
感谢大佬 完美解决
