### ISSUE TITLE
百合会签到失效

### ISSUE THREAD

**Issue by jckling** [jckling/Daily-Bonus#18]
本地挂代理测试发现这个问题：https://www.dismall.com/thread-12232-1-1.html

估计和 cloudflare 有关，难顶

**Comment by jckling** [comment]
github action 实在打印不了 response

明天试试 send file，https://github.com/python-telegram-bot/python-telegram-bot

**Comment by jckling** [comment]
可能和这个有关 [Python3 requests not properly encoding spaces](https://stackoverflow.com/questions/75692453/python3-requests-not-properly-encoding-spaces)

**Comment by MoTingFeng** [comment]
我的这两天也出现了签到不了的情况，推送显示的是未知错误，操作显示的是成功
这是操作日志
[https://github.com/jckling/Daily-Bonus/actions/runs/6216468108/job/16870350154](url)

**Comment by jckling** [comment]
> github action 实在打印不了 response
> 
> 明天试试 send file
> 
> * [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot)
> * [sendDocument](https://core.telegram.org/bots/api#senddocument)

请求头中注释掉 `Accept-Encoding` 即可

**Comment by jckling** [comment]
注册本地 runner 运行可完成签到
