### ISSUE TITLE
大佬，百度贴吧签到现在还支持吗，我是不是维护个DBUSS就可以了呀

### ISSUE THREAD

**Issue by RickHunterS** [jckling/Daily-Bonus#8]

**Comment by jckling** [comment]
dev 分支的签到功能是基于 [Sitoi/dailycheckin](https://github.com/Sitoi/dailycheckin) 删减优化的，应该只需要配置 cookie 就可以签到。我之前停了云函数，所以 dev 分支没有再进行测试，不过既然 Sitoi/dailycheckin 没有更新，那么应该是同步且有效的。
